name: SketchAI
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    iOS: '16.0'
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

# Configuration Files
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configurations/Debug.xcconfig
  Release: Configurations/Release.xcconfig

packages: {}

targets:
  SketchAI:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources:
      - path: .
        excludes:
          - "build/**"
          - "**/*.app"
          - "**/.git"
          - "**/xcodegen.zip"
          - "SketchAI.xcodeproj/**"
          - "**/*.ipa"
          - "**/*.xcarchive"
          - ".github/**"
          - "*.md"
          - "*.yml"
          - "*.sh"
          - "**/*.md"
          - "**/*.sh"
          - "**/*.wat"
          - "Scripts/**"
          - "Configurations/**"
          - "Tests/**"
          - "LaunchScreen.storyboard"
          - "xcodegen/**"
          - "xcodegen.zip"
    resources:
      - path: Assets/ReferenceImages.xcassets
      - path: LaunchScreen.storyboard
      - path: PrivacyInfo.xcprivacy
    dependencies:
      - sdk: Foundation.framework
      - sdk: SwiftUI.framework
      - sdk: UIKit.framework
      - sdk: Combine.framework
      - sdk: CoreData.framework
      - sdk: Vision.framework
      - sdk: AVFoundation.framework
      - sdk: PencilKit.framework
      - sdk: PhotosUI.framework
      - sdk: StoreKit.framework
      - sdk: CoreGraphics.framework
      - sdk: CoreImage.framework
      - sdk: CoreHaptics.framework
      - sdk: AudioToolbox.framework
      - sdk: UserNotifications.framework
      - sdk: AuthenticationServices.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.sketchai
        PRODUCT_NAME: SketchAI
        SWIFT_VERSION: 5.9
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        INFOPLIST_FILE: Info.plist
        CODE_SIGNING_ALLOWED: YES
        ALWAYS_SEARCH_USER_PATHS: NO
        CLANG_ENABLE_OBJC_ARC: YES
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
        CLANG_WARN_BOOL_CONVERSION: YES
        CLANG_WARN_COMMA: YES
        CLANG_WARN_CONSTANT_CONVERSION: YES
        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
        CLANG_WARN_DOCUMENTATION_COMMENTS: YES
        CLANG_WARN_EMPTY_BODY: YES
        CLANG_WARN_ENUM_CONVERSION: YES
        CLANG_WARN_INFINITE_RECURSION: YES
        CLANG_WARN_INT_CONVERSION: YES
        CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
        CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
        CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
        CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
        CLANG_WARN_STRICT_PROTOTYPES: YES
        CLANG_WARN_SUSPICIOUS_MOVE: YES
        CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
        CLANG_WARN_UNREACHABLE_CODE: YES
        CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
        GCC_C_LANGUAGE_STANDARD: gnu11
        GCC_NO_COMMON_BLOCKS: YES
        GCC_WARN_64_TO_32_BIT_CONVERSION: YES
        GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
        GCC_WARN_UNDECLARED_SELECTOR: YES
        GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
        GCC_WARN_UNUSED_FUNCTION: YES
        GCC_WARN_UNUSED_VARIABLE: YES
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
        MTL_FAST_MATH: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_STRICT_CONCURRENCY: targeted
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        # Xcode 16 asset catalog fixes - prevent simulator runtime version conflicts
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: NO
        ASSETCATALOG_COMPILER_OPTIMIZATION: space
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: NO
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOLS: NO
        ASSETCATALOG_COMPILER_SKIP_VALIDATION: NO
        # SDK and runtime version fixes
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        VALID_ARCHS: "arm64 arm64e"
        ARCHS: "arm64"
        # Force device-only compilation to avoid simulator runtime issues
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        TARGETED_DEVICE_FAMILY: "1,2"
        # Exclude simulator architectures to prevent runtime conflicts
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: "arm64"
        # Force device-only asset catalog compilation
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        # Disable all simulator-related asset catalog features
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: NO
        ASSETCATALOG_COMPILER_OPTIMIZATION: space
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: NO
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOLS: NO
        ASSETCATALOG_COMPILER_SKIP_VALIDATION: NO
        # REQUIRED FOR FULL SCREEN SUPPORT - DO NOT REMOVE
        UIRequiresFullScreen: YES
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIViewControllerBasedStatusBarAppearance: NO
        UILaunchStoryboardName: LaunchScreen
        SUPPORTS_IPHONE: YES
        SUPPORTS_IPAD: YES
        
        # Device family support (1=iPhone, 2=iPad)
        TARGETED_DEVICE_FAMILY: "1,2"
        
        # Interface orientations for iPhone
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        
        # Interface orientations for iPad  
        "UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
      debug:
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        ENABLE_TESTABILITY: YES
        GCC_OPTIMIZATION_LEVEL: 0
        ONLY_ACTIVE_ARCH: YES
        CODE_SIGN_ENTITLEMENTS: SketchAI.entitlements
      release:
        SWIFT_OPTIMIZATION_LEVEL: -O
        ENABLE_TESTABILITY: NO
        GCC_OPTIMIZATION_LEVEL: s
        ONLY_ACTIVE_ARCH: NO
        VALIDATE_PRODUCT: YES
        CODE_SIGN_ENTITLEMENTS: SketchAI.entitlements
    info:
      path: Info.plist
      properties:
        # CRITICAL: Launch screen reference for full screen support
        UILaunchStoryboardName: LaunchScreen
        
        # Device support
        UIRequiresFullScreen: true
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIViewControllerBasedStatusBarAppearance: false
        
        # Interface orientations for iPhone
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        
        # Interface orientations for iPad
        "UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  SketchAITests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: '16.0'
    sources:
      - path: Tests
    dependencies:
      - target: SketchAI
      - framework: XCTest
    settings:
      base:
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/SketchAI.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/SketchAI
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.sketchai.tests

schemes:
  SketchAI:
    build:
      targets:
        SketchAI: all
        SketchAITests: [test]
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug 1": true
        "-com.apple.CoreData.SQLDebug 1": true
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    test:
      config: Debug
      targets:
        - SketchAITests
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug 1": true
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release